version: '3.8'

services:
  db:
    image: postgres
    container_name: library-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
